<?php

$lang['en'] += array(
	//Newcomers
	'newcomers.getting_started' => 'Getting Started with Peercoin',
	'newcomers.downlaod_wallet' => 'Download wallet software',
	'newcomers.download_wallet_desc' => 'Head on over to the <a href="wallet">download page</a>, where you can grab the program you’ll need to store and manage your new coins.',
	'newcomers.buy_from_exchange' => 'Buy from an exchange',
	'newcomers.buy_from_exchange_desc' => 'Send your money to a <a href="exchanges">Peercoin exchange</a>, where you’ll be able to buy from other traders in the open market.',
	'newcomers.withdraw_coins' => 'Withdraw your coins',
	'newcomers.withdraw_coins_desc' => 'Take possession of your peercoins by sending them to an address generated by the wallet software. This will protect you in the event that the exchange closes its doors while your money is inside.',
	'newcomers.learn_more' => 'Learn More',
	'newcomers.learn_more_desc' => 'Now that you have coins in your wallet, it’s time to learn how to grow your investment with <a href="minting">Peercoin Minting</a>.',

);

$lang['no'] += array(
	//Newcomers
	'newcomers.getting_started' => 'Komme I Gang Med Peercoin',
	'newcomers.downlaod_wallet' => 'Last ned lommebok programvaren',
	'newcomers.download_wallet_desc' => 'Gå over til <a href="wallet">nedlastingssiden</a>. Der kan du hente programmet du trenger for å lagre og bruke dine nykjøpte mynter.',
	'newcomers.buy_from_exchange' => 'Kjøp på en børs',
	'newcomers.buy_from_exchange_desc' => 'Sende penger til en <a href="exchanges">børs som støtter peercoin</a>, hvor du vil kunne kjøpe fra andre i markedet.',
	'newcomers.withdraw_coins' => 'Uttak av dine mynter',
	'newcomers.withdraw_coins_desc' => 'Send dine mynter til en adresse generert av lommeboken. Dette vil beskytte deg i tilfelle at børsen stenger dørene mens dine penger er der inne.',
	'newcomers.learn_more' => 'Lær Mer',
	'newcomers.learn_more_desc' => 'Nå som du har mynter i lommeboken din, er det på tide å lære hvordan du kan øke beholdningen din ved å <a href="minting">prege peercoins</a>.',

);

$lang['it'] += array(
	//Newcomers
	'newcomers.getting_started' => 'Comincia subito con Peercoin',
	'newcomers.downlaod_wallet' => 'Scarica il portafoglio software',
	'newcomers.download_wallet_desc' => 'Vai sulla <a href="wallet">pagina per il download</a>, dove puoi scaricare il programma di cui avrai bisogno per risparmiare e gestire le tue nuove monete.',
	'newcomers.buy_from_exchange' => 'Compra da un exchange',
	'newcomers.buy_from_exchange_desc' => 'Invia denaro ad un <a href="exchanges">exchange Peercoin</a>, dove potrai comprare da altri traders in un mercato aperto.',
	'newcomers.withdraw_coins' => 'Scarica le tue monete',
	'newcomers.withdraw_coins_desc' => 'Invia i tuoi peercoins ad un indirizzo generato dal software portafoglio. Questo ti proteggerà in caso un exchange fallisce mentre ha il tuo denaro.',
	'newcomers.learn_more' => 'Scopri di più',
	'newcomers.learn_more_desc' => 'Adesso che hai le tue monete nel tuo portafoglio, è il momento di imparare come crescere il tuo investimento con la <a href="minting">coniazione diPeercoin</a>.',

);



?>
