<?php

//mining

$locale_strings['en']['get_peercoins_mining'] = "Peercoin Pool Mining Guide";
$locale_strings['cat']['get_peercoins_mining'] = "Peercoin Pool Mining Guide";
$locale_strings['es']['get_peercoins_mining'] = "Peercoin Pool Mining Guide";
$locale_strings['fr']['get_peercoins_mining'] = "Guide pour les coopératives d'extraction de peercoins";
$locale_strings['gr']['get_peercoins_mining'] = "Peercoin Pool Mining Guide";
$locale_strings['it']['get_peercoins_mining'] = "Peercoin Pool Mining Guide";
$locale_strings['no']['get_peercoins_mining'] = "Peercoin Pool Mining Guide";
$locale_strings['ru']['get_peercoins_mining'] = "Peercoin Pool Mining Guide";
$locale_strings['zh']['get_peercoins_mining'] = "Peercoin Pool Mining Guide";

$locale_strings['en']['get_peercoins_introduction'] = "Introduction";
$locale_strings['cat']['get_peercoins_introduction'] = "Introduction";
$locale_strings['es']['get_peercoins_introduction'] = "Introduction";
$locale_strings['fr']['get_peercoins_introduction'] = "Introduction";
$locale_strings['gr']['get_peercoins_introduction'] = "Introduction";
$locale_strings['it']['get_peercoins_introduction'] = "Introduction";
$locale_strings['no']['get_peercoins_introduction'] = "Introduction";
$locale_strings['ru']['get_peercoins_introduction'] = "Introduction";
$locale_strings['zh']['get_peercoins_introduction'] = "Introduction";

$locale_strings['en']['get_peercoins_intro1'] = "Peercoin is a hybrid Proof-Of-Work / Proof-Of-Stake coin that uses the same proof-of-work algorithm as Bitcoin. This means you can mine Peercoin with GPUs, FGPAs and ASICs using Bitcoin mining software. Through Peercoin's increasing popularity, the transition to proof-of-stake, and the decreasing return on mining, competition for blocks becomes more fierce.";
$locale_strings['cat']['get_peercoins_intro1'] = "Peercoin is a hybrid Proof-Of-Work / Proof-Of-Stake coin that uses the same proof-of-work algorithm as Bitcoin. This means you can mine Peercoin with GPUs, FGPAs and ASICs using Bitcoin mining software. Through Peercoin's increasing popularity, the transition to proof-of-stake, and the decreasing return on mining, competition for blocks becomes more fierce.";
$locale_strings['es']['get_peercoins_intro1'] = "Peercoin is a hybrid Proof-Of-Work / Proof-Of-Stake coin that uses the same proof-of-work algorithm as Bitcoin. This means you can mine Peercoin with GPUs, FGPAs and ASICs using Bitcoin mining software. Through Peercoin's increasing popularity, the transition to proof-of-stake, and the decreasing return on mining, competition for blocks becomes more fierce.";
$locale_strings['fr']['get_peercoins_intro1'] = "Peercoin utilise un système hybride Preuve-de-travail/Preuve-de-part dont l'algorithme de preuve-de-travail est identique à celui utilisé par Bitcoin. Ceci signifie que vous pouvez extraire des peercoins avec des GPU, des FPGA ou des ASIC en utilisant un logiciel d'extraction de bitcoins. À cause de la popularité croissante de Peercoin, de la transition vers la preuve de part, et des gains d'extraction décroissants, la compétition pour générer les blocs devient plus féroce.";
$locale_strings['gr']['get_peercoins_intro1'] = "Peercoin is a hybrid Proof-Of-Work / Proof-Of-Stake coin that uses the same proof-of-work algorithm as Bitcoin. This means you can mine Peercoin with GPUs, FGPAs and ASICs using Bitcoin mining software. Through Peercoin's increasing popularity, the transition to proof-of-stake, and the decreasing return on mining, competition for blocks becomes more fierce.";
$locale_strings['it']['get_peercoins_intro1'] = "Peercoin is a hybrid Proof-Of-Work / Proof-Of-Stake coin that uses the same proof-of-work algorithm as Bitcoin. This means you can mine Peercoin with GPUs, FGPAs and ASICs using Bitcoin mining software. Through Peercoin's increasing popularity, the transition to proof-of-stake, and the decreasing return on mining, competition for blocks becomes more fierce.";
$locale_strings['no']['get_peercoins_intro1'] = "Peercoin is a hybrid Proof-Of-Work / Proof-Of-Stake coin that uses the same proof-of-work algorithm as Bitcoin. This means you can mine Peercoin with GPUs, FGPAs and ASICs using Bitcoin mining software. Through Peercoin's increasing popularity, the transition to proof-of-stake, and the decreasing return on mining, competition for blocks becomes more fierce.";
$locale_strings['ru']['get_peercoins_intro1'] = "Peercoin is a hybrid Proof-Of-Work / Proof-Of-Stake coin that uses the same proof-of-work algorithm as Bitcoin. This means you can mine Peercoin with GPUs, FGPAs and ASICs using Bitcoin mining software. Through Peercoin's increasing popularity, the transition to proof-of-stake, and the decreasing return on mining, competition for blocks becomes more fierce.";
$locale_strings['zh']['get_peercoins_intro1'] = "Peercoin is a hybrid Proof-Of-Work / Proof-Of-Stake coin that uses the same proof-of-work algorithm as Bitcoin. This means you can mine Peercoin with GPUs, FGPAs and ASICs using Bitcoin mining software. Through Peercoin's increasing popularity, the transition to proof-of-stake, and the decreasing return on mining, competition for blocks becomes more fierce.";

$locale_strings['en']['get_peercoins_intro2'] = "Even with powerful hardware it is difficult to mine alone. Mining pools combine the power of all participants to find blocks, and share the reward proportionally based on shares. These guides show you how to poolmine at some of the largest PPC pools. Also make sure to take a look at our <a href=\"minting\">Minting Guide</a>, as you can also earn up 1% on top of your mining rewards.";
$locale_strings['cat']['get_peercoins_intro2'] = "Even with powerful hardware it is difficult to mine alone. Mining pools combine the power of all participants to find blocks, and share the reward proportionally based on shares. These guides show you how to poolmine at some of the largest PPC pools. Also make sure to take a look at our <a href=\"minting\">Minting Guide</a>, as you can also earn up 1% on top of your mining rewards.";
$locale_strings['es']['get_peercoins_intro2'] = "Even with powerful hardware it is difficult to mine alone. Mining pools combine the power of all participants to find blocks, and share the reward proportionally based on shares. These guides show you how to poolmine at some of the largest PPC pools. Also make sure to take a look at our <a href=\"minting\">Minting Guide</a>, as you can also earn up 1% on top of your mining rewards.";
$locale_strings['fr']['get_peercoins_intro2'] = "Même avec un matériel puissant il est difficile d'extraire seul. Les coopératives de mineurs combinent la puissance de tous ses participants pour trouver des blocs et partager les gains en fonction de la part de chacun. Les guides suivants vous montreront comment vous joindre à certaines des plus grosses coopératives PPC. Assurez-vous aussi de jeter un oeil au <a href=\"minting\">Guide de frappe</a>, car vous pouvez gagner 1% de plus sur vos gains d'extraction.";
$locale_strings['gr']['get_peercoins_intro2'] = "Even with powerful hardware it is difficult to mine alone. Mining pools combine the power of all participants to find blocks, and share the reward proportionally based on shares. These guides show you how to poolmine at some of the largest PPC pools. Also make sure to take a look at our <a href=\"minting\">Minting Guide</a>, as you can also earn up 1% on top of your mining rewards.";
$locale_strings['it']['get_peercoins_intro2'] = "Even with powerful hardware it is difficult to mine alone. Mining pools combine the power of all participants to find blocks, and share the reward proportionally based on shares. These guides show you how to poolmine at some of the largest PPC pools. Also make sure to take a look at our <a href=\"minting\">Minting Guide</a>, as you can also earn up 1% on top of your mining rewards.";
$locale_strings['no']['get_peercoins_intro2'] = "Even with powerful hardware it is difficult to mine alone. Mining pools combine the power of all participants to find blocks, and share the reward proportionally based on shares. These guides show you how to poolmine at some of the largest PPC pools. Also make sure to take a look at our <a href=\"minting\">Minting Guide</a>, as you can also earn up 1% on top of your mining rewards.";
$locale_strings['ru']['get_peercoins_intro2'] = "Even with powerful hardware it is difficult to mine alone. Mining pools combine the power of all participants to find blocks, and share the reward proportionally based on shares. These guides show you how to poolmine at some of the largest PPC pools. Also make sure to take a look at our <a href=\"minting\">Minting Guide</a>, as you can also earn up 1% on top of your mining rewards.";
$locale_strings['zh']['get_peercoins_intro2'] = "Even with powerful hardware it is difficult to mine alone. Mining pools combine the power of all participants to find blocks, and share the reward proportionally based on shares. These guides show you how to poolmine at some of the largest PPC pools. Also make sure to take a look at our <a href=\"minting\">Minting Guide</a>, as you can also earn up 1% on top of your mining rewards.";

$locale_strings['en']['get_peercoins_set_up'] = "1) Set up a Peercoin wallet";
$locale_strings['cat']['get_peercoins_set_up'] = "1) Set up a Peercoin wallet";
$locale_strings['es']['get_peercoins_set_up'] = "1) Set up a Peercoin wallet";
$locale_strings['fr']['get_peercoins_set_up'] = "1) Mettez en place un portefeuille Peercoin";
$locale_strings['gr']['get_peercoins_set_up'] = "1) Set up a Peercoin wallet";
$locale_strings['it']['get_peercoins_set_up'] = "1) Set up a Peercoin wallet";
$locale_strings['no']['get_peercoins_set_up'] = "1) Set up a Peercoin wallet";
$locale_strings['ru']['get_peercoins_set_up'] = "1) Set up a Peercoin wallet";
$locale_strings['zh']['get_peercoins_set_up'] = "1) Set up a Peercoin wallet";

$locale_strings['en']['get_peercoins_set_up_desc'] = "<a href=\"downloads\">Download the Peercoin wallet</a> if you did not do this already.";
$locale_strings['cat']['get_peercoins_set_up_desc'] = "<a href=\"downloads\">Download the Peercoin wallet</a> if you did not do this already.";
$locale_strings['es']['get_peercoins_set_up_desc'] = "<a href=\"downloads\">Download the Peercoin wallet</a> if you did not do this already.";
$locale_strings['fr']['get_peercoins_set_up_desc'] = "<a href=\"downloads\">Téléchargez le portefeuille Peercoin</a> si vous ne l'avez pas déjà fait.";
$locale_strings['gr']['get_peercoins_set_up_desc'] = "<a href=\"downloads\">Download the Peercoin wallet</a> if you did not do this already.";
$locale_strings['it']['get_peercoins_set_up_desc'] = "<a href=\"downloads\">Download the Peercoin wallet</a> if you did not do this already.";
$locale_strings['no']['get_peercoins_set_up_desc'] = "<a href=\"downloads\">Download the Peercoin wallet</a> if you did not do this already.";
$locale_strings['ru']['get_peercoins_set_up_desc'] = "<a href=\"downloads\">Download the Peercoin wallet</a> if you did not do this already.";
$locale_strings['zh']['get_peercoins_set_up_desc'] = "<a href=\"downloads\">Download the Peercoin wallet</a> if you did not do this already.";

$locale_strings['en']['get_peercoins_sign_up'] = "2) Sign up at a mining pool";
$locale_strings['cat']['get_peercoins_sign_up'] = "2) Sign up at a mining pool";
$locale_strings['es']['get_peercoins_sign_up'] = "2) Sign up at a mining pool";
$locale_strings['fr']['get_peercoins_sign_up'] = "2) Inscrivez-vous à une coopérative de mineurs";
$locale_strings['gr']['get_peercoins_sign_up'] = "2) Sign up at a mining pool";
$locale_strings['it']['get_peercoins_sign_up'] = "2) Sign up at a mining pool";
$locale_strings['no']['get_peercoins_sign_up'] = "2) Sign up at a mining pool";
$locale_strings['ru']['get_peercoins_sign_up'] = "2) Sign up at a mining pool";
$locale_strings['zh']['get_peercoins_sign_up'] = "2) Sign up at a mining pool";

$locale_strings['en']['get_peercoins_sign_up_desc'] = "You can find a list of pools in the <a href=\"resources#pools\">resources page</a>. Here you can find instructions to join some of these pools.";
$locale_strings['cat']['get_peercoins_sign_up_desc'] = "You can find a list of pools in the <a href=\"resources#pools\">resources page</a>. Here you can find instructions to join some of these pools.";
$locale_strings['es']['get_peercoins_sign_up_desc'] = "You can find a list of pools in the <a href=\"resources#pools\">resources page</a>. Here you can find instructions to join some of these pools.";
$locale_strings['fr']['get_peercoins_sign_up_desc'] = "Vous trouverez une liste de coopératives sur la <a href=\"resources#pools\">page des ressources</a>. Vous trouverez ci-dessous des instructions pour rejoindre certaines de ces coopératives.";
$locale_strings['gr']['get_peercoins_sign_up_desc'] = "You can find a list of pools in the <a href=\"resources#pools\">resources page</a>. Here you can find instructions to join some of these pools.";
$locale_strings['it']['get_peercoins_sign_up_desc'] = "You can find a list of pools in the <a href=\"resources#pools\">resources page</a>. Here you can find instructions to join some of these pools.";
$locale_strings['no']['get_peercoins_sign_up_desc'] = "You can find a list of pools in the <a href=\"resources#pools\">resources page</a>. Here you can find instructions to join some of these pools.";
$locale_strings['ru']['get_peercoins_sign_up_desc'] = "You can find a list of pools in the <a href=\"resources#pools\">resources page</a>. Here you can find instructions to join some of these pools.";
$locale_strings['zh']['get_peercoins_sign_up_desc'] = "You can find a list of pools in the <a href=\"resources#pools\">resources page</a>. Here you can find instructions to join some of these pools.";


//minting

$locale_strings['en']['get_peercoins_minting'] = "What is Proof-of-Stake/Minting?";
$locale_strings['cat']['get_peercoins_minting'] = "What is Proof-of-Stake/Minting?";
$locale_strings['es']['get_peercoins_minting'] = "What is Proof-of-Stake/Minting?";
$locale_strings['fr']['get_peercoins_minting'] = "Qu'est ce que la Preuve-de-part/Frapper la monnaie";
$locale_strings['gr']['get_peercoins_minting'] = "What is Proof-of-Stake/Minting?";
$locale_strings['it']['get_peercoins_minting'] = "What is Proof-of-Stake/Minting?";
$locale_strings['no']['get_peercoins_minting'] = "What is Proof-of-Stake/Minting?";
$locale_strings['ru']['get_peercoins_minting'] = "What is Proof-of-Stake/Minting?";
$locale_strings['zh']['get_peercoins_minting'] = "What is Proof-of-Stake/Minting?";

$locale_strings['en']['get_peercoins_minting_intro'] = "Introduction";
$locale_strings['cat']['get_peercoins_minting_intro'] = "Introduction";
$locale_strings['es']['get_peercoins_minting_intro'] = "Introduction";
$locale_strings['fr']['get_peercoins_minting_intro'] = "Introduction";
$locale_strings['gr']['get_peercoins_minting_intro'] = "Introduction";
$locale_strings['it']['get_peercoins_minting_intro'] = "Introduction";
$locale_strings['no']['get_peercoins_minting_intro'] = "Introduction";
$locale_strings['ru']['get_peercoins_minting_intro'] = "Introduction";
$locale_strings['zh']['get_peercoins_minting_intro'] = "Introduction";

$locale_strings['en']['get_peercoins_minting_intro_desc'] = "Peercoin (PPC) uses a novel, green, and very interesting method of network validation and mining. Most alternative cryptocurrencies in existence are forks of Bitcoin with changed mining parameters or different mining algorithms. Miners maintain the network and check transactions, while spending a lot of energy on cryptographic brute force puzzles. <a href=\"https://blockchain.info/stats\">Blockchain.info</a> estimates that mid December 2013, Bitcoin mining takes up 22 million dollars or 150.000 megawatts of energy <em>per day</em>. Peercoin also started out as a Proof-Of-Work network. But as more blocks and coins have been mined, the network switches slowly to Proof-Of-Stake validation. With it we also switch to a new approach of securing the network. In Peercoin terms this process of generating coins by stake is called minting. And if you have a stake in Peercoin (PPC) coins, you can mint too!</p><p>Proof-of-work and proof-of-stake are methods of securing cryptocurrency networks. Bitcoin uses a purely proof-of-work-based system, in which the probability of solving a block (and getting the block reward) depends on hashrate. On the Bitcoin network, rewards are distributed solely according to work done by miners.</p><p>Peercoin uses a hybrid proof-of-work/proof-of-stake system. Instead of being dependent on hashing power available, proof-of-stake blocks are distributed according to possession of the coins. For example, an individual possessing 1% of all Peercoins currently in existence would be able to mint 1% of the proof-of-stake blocks. Notice that the term \"mint\" is used in generation of proof-of-stake blocks. The term \"mine\" refers specifically to the generation of proof-of-work blocks. Minting can be performed by running a full node of the Peercoin client and does not require many resources.</p><p>Just like proof-of-work blocks, proof-of-stake blocks generate currency rewards. To generate proof-of-stake blocks, a user sends already-possessed coins to himself in exchange for a preset reward. This reward is currently set at about 1% per year. These transactions increase the \"consumed coin age\" of the blockchain, a property that Peercoin uses to determine the trustworthiness of the blockchain.";
$locale_strings['cat']['get_peercoins_minting_intro_desc'] = "Peercoin (PPC) uses a novel, green, and very interesting method of network validation and mining. Most alternative cryptocurrencies in existence are forks of Bitcoin with changed mining parameters or different mining algorithms. Miners maintain the network and check transactions, while spending a lot of energy on cryptographic brute force puzzles. <a href=\"https://blockchain.info/stats\">Blockchain.info</a> estimates that mid December 2013, Bitcoin mining takes up 22 million dollars or 150.000 megawatts of energy <em>per day</em>. Peercoin also started out as a Proof-Of-Work network. But as more blocks and coins have been mined, the network switches slowly to Proof-Of-Stake validation. With it we also switch to a new approach of securing the network. In Peercoin terms this process of generating coins by stake is called minting. And if you have a stake in Peercoin (PPC) coins, you can mint too!</p><p>Proof-of-work and proof-of-stake are methods of securing cryptocurrency networks. Bitcoin uses a purely proof-of-work-based system, in which the probability of solving a block (and getting the block reward) depends on hashrate. On the Bitcoin network, rewards are distributed solely according to work done by miners.</p><p>Peercoin uses a hybrid proof-of-work/proof-of-stake system. Instead of being dependent on hashing power available, proof-of-stake blocks are distributed according to possession of the coins. For example, an individual possessing 1% of all Peercoins currently in existence would be able to mint 1% of the proof-of-stake blocks. Notice that the term \"mint\" is used in generation of proof-of-stake blocks. The term \"mine\" refers specifically to the generation of proof-of-work blocks. Minting can be performed by running a full node of the Peercoin client and does not require many resources.</p><p>Just like proof-of-work blocks, proof-of-stake blocks generate currency rewards. To generate proof-of-stake blocks, a user sends already-possessed coins to himself in exchange for a preset reward. This reward is currently set at about 1% per year. These transactions increase the \"consumed coin age\" of the blockchain, a property that Peercoin uses to determine the trustworthiness of the blockchain.";
$locale_strings['es']['get_peercoins_minting_intro_desc'] = "Peercoin (PPC) uses a novel, green, and very interesting method of network validation and mining. Most alternative cryptocurrencies in existence are forks of Bitcoin with changed mining parameters or different mining algorithms. Miners maintain the network and check transactions, while spending a lot of energy on cryptographic brute force puzzles. <a href=\"https://blockchain.info/stats\">Blockchain.info</a> estimates that mid December 2013, Bitcoin mining takes up 22 million dollars or 150.000 megawatts of energy <em>per day</em>. Peercoin also started out as a Proof-Of-Work network. But as more blocks and coins have been mined, the network switches slowly to Proof-Of-Stake validation. With it we also switch to a new approach of securing the network. In Peercoin terms this process of generating coins by stake is called minting. And if you have a stake in Peercoin (PPC) coins, you can mint too!</p><p>Proof-of-work and proof-of-stake are methods of securing cryptocurrency networks. Bitcoin uses a purely proof-of-work-based system, in which the probability of solving a block (and getting the block reward) depends on hashrate. On the Bitcoin network, rewards are distributed solely according to work done by miners.</p><p>Peercoin uses a hybrid proof-of-work/proof-of-stake system. Instead of being dependent on hashing power available, proof-of-stake blocks are distributed according to possession of the coins. For example, an individual possessing 1% of all Peercoins currently in existence would be able to mint 1% of the proof-of-stake blocks. Notice that the term \"mint\" is used in generation of proof-of-stake blocks. The term \"mine\" refers specifically to the generation of proof-of-work blocks. Minting can be performed by running a full node of the Peercoin client and does not require many resources.</p><p>Just like proof-of-work blocks, proof-of-stake blocks generate currency rewards. To generate proof-of-stake blocks, a user sends already-possessed coins to himself in exchange for a preset reward. This reward is currently set at about 1% per year. These transactions increase the \"consumed coin age\" of the blockchain, a property that Peercoin uses to determine the trustworthiness of the blockchain.";
$locale_strings['fr']['get_peercoins_minting_intro_desc'] = "Peercoin (PPC) utilise une méthode innovante, écologique et très intéressante pour valider les blocs du réseau. La plupart des crypto-monnaies alternatives existantes sont des forks de Bitcoin avec des changements de paramètres ou d'algorithme d'extraction. Les mineurs maintiennent le réseau et vérifient les transactions en dépensant énormément d'énergie pour résoudre des puzzles cryptographiques par force brute. <a href=\"https://blockchain.info/stats\">Blockchain.info</a> estime que mi-décembre 2013, l'extraction de bitcoins coûtait 22 millions de dollars ou 150 000 megawatts d'énergie <em>par jour</em>. Peercoin a aussi commencé comme un réseau Preuve-de-travail. Mais au fur et à mesure que de nouvelles pièces sont extraites, le réseau passe progressivement à la validation par Preuve-de-part. On passe ainsi à une nouvelle approche pour sécuriser le réseau. Dans le jargon de Peercoin on appelle frappe ce procédé de génération de monnaie par preuve-de-part. Et si vous avez une part des pièces de Peercoin (PPC), vous pouvez frapper la monnaie vous aussi !</p><p>La preuve-de-travail et la preuve-de-part sont des méthode de sécurisation des réseaux des crypto-monnaies. Bitcoin utilise un système basé sur la preuve-de-travail, dans lequel la probabilité de trouver un bloc (et de gagner la récompense du bloc) dépend de la vitesse de hachage. Dans le réseau Bitcoin, les récompenses sont distribuées uniquement selon le travail réalisé par les mineurs.</p><p>Peercoin utilise un système hybride preuve-de-travail/preuve-de-part. Au lieu de dépendre de la puissance de hachage disponible, la preuve-de-part dépend de la possession de pièces. Par exemple, un individu possédant 1% de tous les peercoins actuellement en existence pourrait frapper 1% des blocs preuve-de-part. Notez que le terme \"frappe\" est utilisé pour la génération des blocs preuve-de-part. Le terme \"extraction\" se réfère spécifiquement à la génération de blocs preuve-de-travail. La frappe de monnaie peut être réalisée en laissant tourner le client Peercoin comme noeud complet du réseau, et cela ne nécessite pas beaucoup de ressources.</p><p>Comme les blocs preuve-de-travail, les blocs preuve-de-part génèrent des récompenses monétaires. Pour générer un bloc preuve-de-part, un utilisateur s'envoie à lui-même des pièces qu'il possède déjà en échange d'une récompense prédéterminée. Cette récompense est actuellement fixée à environ 1% par an. Ces transactions augmentent \"l'age-pièce consommé\" de la chaîne de blocs, une propriété que Peercoin utilisé pour définir la confiance dans la chaîne de blocs.";
$locale_strings['gr']['get_peercoins_minting_intro_desc'] = "Peercoin (PPC) uses a novel, green, and very interesting method of network validation and mining. Most alternative cryptocurrencies in existence are forks of Bitcoin with changed mining parameters or different mining algorithms. Miners maintain the network and check transactions, while spending a lot of energy on cryptographic brute force puzzles. <a href=\"https://blockchain.info/stats\">Blockchain.info</a> estimates that mid December 2013, Bitcoin mining takes up 22 million dollars or 150.000 megawatts of energy <em>per day</em>. Peercoin also started out as a Proof-Of-Work network. But as more blocks and coins have been mined, the network switches slowly to Proof-Of-Stake validation. With it we also switch to a new approach of securing the network. In Peercoin terms this process of generating coins by stake is called minting. And if you have a stake in Peercoin (PPC) coins, you can mint too!</p><p>Proof-of-work and proof-of-stake are methods of securing cryptocurrency networks. Bitcoin uses a purely proof-of-work-based system, in which the probability of solving a block (and getting the block reward) depends on hashrate. On the Bitcoin network, rewards are distributed solely according to work done by miners.</p><p>Peercoin uses a hybrid proof-of-work/proof-of-stake system. Instead of being dependent on hashing power available, proof-of-stake blocks are distributed according to possession of the coins. For example, an individual possessing 1% of all Peercoins currently in existence would be able to mint 1% of the proof-of-stake blocks. Notice that the term \"mint\" is used in generation of proof-of-stake blocks. The term \"mine\" refers specifically to the generation of proof-of-work blocks. Minting can be performed by running a full node of the Peercoin client and does not require many resources.</p><p>Just like proof-of-work blocks, proof-of-stake blocks generate currency rewards. To generate proof-of-stake blocks, a user sends already-possessed coins to himself in exchange for a preset reward. This reward is currently set at about 1% per year. These transactions increase the \"consumed coin age\" of the blockchain, a property that Peercoin uses to determine the trustworthiness of the blockchain.";
$locale_strings['it']['get_peercoins_minting_intro_desc'] = "Peercoin (PPC) uses a novel, green, and very interesting method of network validation and mining. Most alternative cryptocurrencies in existence are forks of Bitcoin with changed mining parameters or different mining algorithms. Miners maintain the network and check transactions, while spending a lot of energy on cryptographic brute force puzzles. <a href=\"https://blockchain.info/stats\">Blockchain.info</a> estimates that mid December 2013, Bitcoin mining takes up 22 million dollars or 150.000 megawatts of energy <em>per day</em>. Peercoin also started out as a Proof-Of-Work network. But as more blocks and coins have been mined, the network switches slowly to Proof-Of-Stake validation. With it we also switch to a new approach of securing the network. In Peercoin terms this process of generating coins by stake is called minting. And if you have a stake in Peercoin (PPC) coins, you can mint too!</p><p>Proof-of-work and proof-of-stake are methods of securing cryptocurrency networks. Bitcoin uses a purely proof-of-work-based system, in which the probability of solving a block (and getting the block reward) depends on hashrate. On the Bitcoin network, rewards are distributed solely according to work done by miners.</p><p>Peercoin uses a hybrid proof-of-work/proof-of-stake system. Instead of being dependent on hashing power available, proof-of-stake blocks are distributed according to possession of the coins. For example, an individual possessing 1% of all Peercoins currently in existence would be able to mint 1% of the proof-of-stake blocks. Notice that the term \"mint\" is used in generation of proof-of-stake blocks. The term \"mine\" refers specifically to the generation of proof-of-work blocks. Minting can be performed by running a full node of the Peercoin client and does not require many resources.</p><p>Just like proof-of-work blocks, proof-of-stake blocks generate currency rewards. To generate proof-of-stake blocks, a user sends already-possessed coins to himself in exchange for a preset reward. This reward is currently set at about 1% per year. These transactions increase the \"consumed coin age\" of the blockchain, a property that Peercoin uses to determine the trustworthiness of the blockchain.";
$locale_strings['no']['get_peercoins_minting_intro_desc'] = "Peercoin (PPC) uses a novel, green, and very interesting method of network validation and mining. Most alternative cryptocurrencies in existence are forks of Bitcoin with changed mining parameters or different mining algorithms. Miners maintain the network and check transactions, while spending a lot of energy on cryptographic brute force puzzles. <a href=\"https://blockchain.info/stats\">Blockchain.info</a> estimates that mid December 2013, Bitcoin mining takes up 22 million dollars or 150.000 megawatts of energy <em>per day</em>. Peercoin also started out as a Proof-Of-Work network. But as more blocks and coins have been mined, the network switches slowly to Proof-Of-Stake validation. With it we also switch to a new approach of securing the network. In Peercoin terms this process of generating coins by stake is called minting. And if you have a stake in Peercoin (PPC) coins, you can mint too!</p><p>Proof-of-work and proof-of-stake are methods of securing cryptocurrency networks. Bitcoin uses a purely proof-of-work-based system, in which the probability of solving a block (and getting the block reward) depends on hashrate. On the Bitcoin network, rewards are distributed solely according to work done by miners.</p><p>Peercoin uses a hybrid proof-of-work/proof-of-stake system. Instead of being dependent on hashing power available, proof-of-stake blocks are distributed according to possession of the coins. For example, an individual possessing 1% of all Peercoins currently in existence would be able to mint 1% of the proof-of-stake blocks. Notice that the term \"mint\" is used in generation of proof-of-stake blocks. The term \"mine\" refers specifically to the generation of proof-of-work blocks. Minting can be performed by running a full node of the Peercoin client and does not require many resources.</p><p>Just like proof-of-work blocks, proof-of-stake blocks generate currency rewards. To generate proof-of-stake blocks, a user sends already-possessed coins to himself in exchange for a preset reward. This reward is currently set at about 1% per year. These transactions increase the \"consumed coin age\" of the blockchain, a property that Peercoin uses to determine the trustworthiness of the blockchain.";
$locale_strings['ru']['get_peercoins_minting_intro_desc'] = "Peercoin (PPC) uses a novel, green, and very interesting method of network validation and mining. Most alternative cryptocurrencies in existence are forks of Bitcoin with changed mining parameters or different mining algorithms. Miners maintain the network and check transactions, while spending a lot of energy on cryptographic brute force puzzles. <a href=\"https://blockchain.info/stats\">Blockchain.info</a> estimates that mid December 2013, Bitcoin mining takes up 22 million dollars or 150.000 megawatts of energy <em>per day</em>. Peercoin also started out as a Proof-Of-Work network. But as more blocks and coins have been mined, the network switches slowly to Proof-Of-Stake validation. With it we also switch to a new approach of securing the network. In Peercoin terms this process of generating coins by stake is called minting. And if you have a stake in Peercoin (PPC) coins, you can mint too!</p><p>Proof-of-work and proof-of-stake are methods of securing cryptocurrency networks. Bitcoin uses a purely proof-of-work-based system, in which the probability of solving a block (and getting the block reward) depends on hashrate. On the Bitcoin network, rewards are distributed solely according to work done by miners.</p><p>Peercoin uses a hybrid proof-of-work/proof-of-stake system. Instead of being dependent on hashing power available, proof-of-stake blocks are distributed according to possession of the coins. For example, an individual possessing 1% of all Peercoins currently in existence would be able to mint 1% of the proof-of-stake blocks. Notice that the term \"mint\" is used in generation of proof-of-stake blocks. The term \"mine\" refers specifically to the generation of proof-of-work blocks. Minting can be performed by running a full node of the Peercoin client and does not require many resources.</p><p>Just like proof-of-work blocks, proof-of-stake blocks generate currency rewards. To generate proof-of-stake blocks, a user sends already-possessed coins to himself in exchange for a preset reward. This reward is currently set at about 1% per year. These transactions increase the \"consumed coin age\" of the blockchain, a property that Peercoin uses to determine the trustworthiness of the blockchain.";
$locale_strings['zh']['get_peercoins_minting_intro_desc'] = "Peercoin (PPC) uses a novel, green, and very interesting method of network validation and mining. Most alternative cryptocurrencies in existence are forks of Bitcoin with changed mining parameters or different mining algorithms. Miners maintain the network and check transactions, while spending a lot of energy on cryptographic brute force puzzles. <a href=\"https://blockchain.info/stats\">Blockchain.info</a> estimates that mid December 2013, Bitcoin mining takes up 22 million dollars or 150.000 megawatts of energy <em>per day</em>. Peercoin also started out as a Proof-Of-Work network. But as more blocks and coins have been mined, the network switches slowly to Proof-Of-Stake validation. With it we also switch to a new approach of securing the network. In Peercoin terms this process of generating coins by stake is called minting. And if you have a stake in Peercoin (PPC) coins, you can mint too!</p><p>Proof-of-work and proof-of-stake are methods of securing cryptocurrency networks. Bitcoin uses a purely proof-of-work-based system, in which the probability of solving a block (and getting the block reward) depends on hashrate. On the Bitcoin network, rewards are distributed solely according to work done by miners.</p><p>Peercoin uses a hybrid proof-of-work/proof-of-stake system. Instead of being dependent on hashing power available, proof-of-stake blocks are distributed according to possession of the coins. For example, an individual possessing 1% of all Peercoins currently in existence would be able to mint 1% of the proof-of-stake blocks. Notice that the term \"mint\" is used in generation of proof-of-stake blocks. The term \"mine\" refers specifically to the generation of proof-of-work blocks. Minting can be performed by running a full node of the Peercoin client and does not require many resources.</p><p>Just like proof-of-work blocks, proof-of-stake blocks generate currency rewards. To generate proof-of-stake blocks, a user sends already-possessed coins to himself in exchange for a preset reward. This reward is currently set at about 1% per year. These transactions increase the \"consumed coin age\" of the blockchain, a property that Peercoin uses to determine the trustworthiness of the blockchain.";

$locale_strings['en']['get_peercoins_minting_efficiency'] = "Efficiency";
$locale_strings['cat']['get_peercoins_minting_efficiency'] = "Efficiency";
$locale_strings['es']['get_peercoins_minting_efficiency'] = "Efficiency";
$locale_strings['fr']['get_peercoins_minting_efficiency'] = "Efficacité";
$locale_strings['gr']['get_peercoins_minting_efficiency'] = "Efficiency";
$locale_strings['it']['get_peercoins_minting_efficiency'] = "Efficiency";
$locale_strings['no']['get_peercoins_minting_efficiency'] = "Efficiency";
$locale_strings['ru']['get_peercoins_minting_efficiency'] = "Efficiency";
$locale_strings['zh']['get_peercoins_minting_efficiency'] = "Efficiency";

$locale_strings['en']['get_peercoins_minting_efficiency_desc'] = "Proof-of-work security is based on hashing power, and consumes a large amount of energy to solve blocks. This means that mining is prohibitively difficult for those that do not have access to powerful hardware and money for electricity. As the Peercoin network switches over to proof-of-stake security over time, minting proof-of-stake blocks provides security in a sustainable and green way without requiring consuming large amounts of energy.";
$locale_strings['cat']['get_peercoins_minting_efficiency_desc'] = "Proof-of-work security is based on hashing power, and consumes a large amount of energy to solve blocks. This means that mining is prohibitively difficult for those that do not have access to powerful hardware and money for electricity. As the Peercoin network switches over to proof-of-stake security over time, minting proof-of-stake blocks provides security in a sustainable and green way without requiring consuming large amounts of energy.";
$locale_strings['es']['get_peercoins_minting_efficiency_desc'] = "Proof-of-work security is based on hashing power, and consumes a large amount of energy to solve blocks. This means that mining is prohibitively difficult for those that do not have access to powerful hardware and money for electricity. As the Peercoin network switches over to proof-of-stake security over time, minting proof-of-stake blocks provides security in a sustainable and green way without requiring consuming large amounts of energy.";
$locale_strings['fr']['get_peercoins_minting_efficiency_desc'] = "La sécurité par preuve-de-travail est basée sur la puissance de hachage, et consomme de grandes quantités d'énergie pour trouver des blocs. Ceci signifie que l'extraction est difficile, voire inaccessible, pour ceux qui ne peuvent pas s'offir suffisament de matériel puissant et d'électricité. Comme le réseau Peercoin passe à la preuve-de-part, frapper des blocs fournit la sécurité de manière durable et écologique en ne nécessitant pas de grandes quantités d'énergie.";
$locale_strings['gr']['get_peercoins_minting_efficiency_desc'] = "Proof-of-work security is based on hashing power, and consumes a large amount of energy to solve blocks. This means that mining is prohibitively difficult for those that do not have access to powerful hardware and money for electricity. As the Peercoin network switches over to proof-of-stake security over time, minting proof-of-stake blocks provides security in a sustainable and green way without requiring consuming large amounts of energy.";
$locale_strings['it']['get_peercoins_minting_efficiency_desc'] = "Proof-of-work security is based on hashing power, and consumes a large amount of energy to solve blocks. This means that mining is prohibitively difficult for those that do not have access to powerful hardware and money for electricity. As the Peercoin network switches over to proof-of-stake security over time, minting proof-of-stake blocks provides security in a sustainable and green way without requiring consuming large amounts of energy.";
$locale_strings['no']['get_peercoins_minting_efficiency_desc'] = "Proof-of-work security is based on hashing power, and consumes a large amount of energy to solve blocks. This means that mining is prohibitively difficult for those that do not have access to powerful hardware and money for electricity. As the Peercoin network switches over to proof-of-stake security over time, minting proof-of-stake blocks provides security in a sustainable and green way without requiring consuming large amounts of energy.";
$locale_strings['ru']['get_peercoins_minting_efficiency_desc'] = "Proof-of-work security is based on hashing power, and consumes a large amount of energy to solve blocks. This means that mining is prohibitively difficult for those that do not have access to powerful hardware and money for electricity. As the Peercoin network switches over to proof-of-stake security over time, minting proof-of-stake blocks provides security in a sustainable and green way without requiring consuming large amounts of energy.";
$locale_strings['zh']['get_peercoins_minting_efficiency_desc'] = "Proof-of-work security is based on hashing power, and consumes a large amount of energy to solve blocks. This means that mining is prohibitively difficult for those that do not have access to powerful hardware and money for electricity. As the Peercoin network switches over to proof-of-stake security over time, minting proof-of-stake blocks provides security in a sustainable and green way without requiring consuming large amounts of energy.";

$locale_strings['en']['get_peercoins_minting_security'] = "Security";
$locale_strings['cat']['get_peercoins_minting_security'] = "Security";
$locale_strings['es']['get_peercoins_minting_security'] = "Security";
$locale_strings['fr']['get_peercoins_minting_security'] = "Sécurité";
$locale_strings['gr']['get_peercoins_minting_security'] = "Security";
$locale_strings['it']['get_peercoins_minting_security'] = "Security";
$locale_strings['no']['get_peercoins_minting_security'] = "Security";
$locale_strings['ru']['get_peercoins_minting_security'] = "Security";
$locale_strings['zh']['get_peercoins_minting_security'] = "Security";

$locale_strings['en']['get_peercoins_minting_security_desc'] = "In a proof-of-work system, the network is secure as long as no one party controls more than 51% of mining power. To perform an attack, a single attacker must be able to outpace the rest of the network in block generation. This may seem unlikely, but Bitcoin mining pools have approached 51% of the network hashrate in the past. At the time of writing, two mining pools control more than 51% of the Bitcoin network; an attack could be performed by coercing just two people (the pool operators) to collude.</p><p>In Peercoin, an attacker would have to possess 51% of the minting power, which means 51% of all coins if everyone is minting. This makes the attack more difficult as it is unlikely one party would end up owning 51% of the wealth, but also acts as a deterrent to attack because an attack would cause the value of the currency to drop. A party that possesses more than 51% of coins has a vested interest in keeping the value of the coins steady or rising.";
$locale_strings['cat']['get_peercoins_minting_security_desc'] = "In a proof-of-work system, the network is secure as long as no one party controls more than 51% of mining power. To perform an attack, a single attacker must be able to outpace the rest of the network in block generation. This may seem unlikely, but Bitcoin mining pools have approached 51% of the network hashrate in the past. At the time of writing, two mining pools control more than 51% of the Bitcoin network; an attack could be performed by coercing just two people (the pool operators) to collude.</p><p>In Peercoin, an attacker would have to possess 51% of the minting power, which means 51% of all coins if everyone is minting. This makes the attack more difficult as it is unlikely one party would end up owning 51% of the wealth, but also acts as a deterrent to attack because an attack would cause the value of the currency to drop. A party that possesses more than 51% of coins has a vested interest in keeping the value of the coins steady or rising.";
$locale_strings['es']['get_peercoins_minting_security_desc'] = "In a proof-of-work system, the network is secure as long as no one party controls more than 51% of mining power. To perform an attack, a single attacker must be able to outpace the rest of the network in block generation. This may seem unlikely, but Bitcoin mining pools have approached 51% of the network hashrate in the past. At the time of writing, two mining pools control more than 51% of the Bitcoin network; an attack could be performed by coercing just two people (the pool operators) to collude.</p><p>In Peercoin, an attacker would have to possess 51% of the minting power, which means 51% of all coins if everyone is minting. This makes the attack more difficult as it is unlikely one party would end up owning 51% of the wealth, but also acts as a deterrent to attack because an attack would cause the value of the currency to drop. A party that possesses more than 51% of coins has a vested interest in keeping the value of the coins steady or rising.";
$locale_strings['fr']['get_peercoins_minting_security_desc'] = "Dans un système par preuve-de-travail, le réseau est sûr tant que personne ne contrôle plus de 51% de la puissance d'extraction. Pour réaliser une attaque, un attaquant doit être capable de surpasser le reste du réseau dans la génération de blocs. Ceci peut sembler improbable, mais des coopératives de mineurs de bitcoins ont déjà approché les 51% de la vitesse de hachage du réseau dans le passé. Au moment de l'écriture de ce paragraphe, deux coopérative de mineurs contrôlent plus de 51% du réseau Bitcoin; une attaque pourrait être exécutée en convaincant juste deux personnes (les opérateurs des coopératives) d'entrer dans le complot.</p><p>Dans Peercoin, un attaquant devrait posséder 51% de la puissance de frappe de monnaie, c'est à dire 51% de toutes les pièces si tout le monde frappe la monnaie. Ceci rend une attaque plus difficile car il est improbable qu'une seule personne se retrouve avec 51% de toute la richesse, mais cela agit aussi comme dissuasif à l'attaque puisque celle-ci causerait une chute de la valeur de la monnaie. Quelqu'un possédant plus de 51% des pièces a un intérêt certain à faire en sorte que leur valeur soit constante ou croissante.";
$locale_strings['gr']['get_peercoins_minting_security_desc'] = "In a proof-of-work system, the network is secure as long as no one party controls more than 51% of mining power. To perform an attack, a single attacker must be able to outpace the rest of the network in block generation. This may seem unlikely, but Bitcoin mining pools have approached 51% of the network hashrate in the past. At the time of writing, two mining pools control more than 51% of the Bitcoin network; an attack could be performed by coercing just two people (the pool operators) to collude.</p><p>In Peercoin, an attacker would have to possess 51% of the minting power, which means 51% of all coins if everyone is minting. This makes the attack more difficult as it is unlikely one party would end up owning 51% of the wealth, but also acts as a deterrent to attack because an attack would cause the value of the currency to drop. A party that possesses more than 51% of coins has a vested interest in keeping the value of the coins steady or rising.";
$locale_strings['it']['get_peercoins_minting_security_desc'] = "In a proof-of-work system, the network is secure as long as no one party controls more than 51% of mining power. To perform an attack, a single attacker must be able to outpace the rest of the network in block generation. This may seem unlikely, but Bitcoin mining pools have approached 51% of the network hashrate in the past. At the time of writing, two mining pools control more than 51% of the Bitcoin network; an attack could be performed by coercing just two people (the pool operators) to collude.</p><p>In Peercoin, an attacker would have to possess 51% of the minting power, which means 51% of all coins if everyone is minting. This makes the attack more difficult as it is unlikely one party would end up owning 51% of the wealth, but also acts as a deterrent to attack because an attack would cause the value of the currency to drop. A party that possesses more than 51% of coins has a vested interest in keeping the value of the coins steady or rising.";
$locale_strings['no']['get_peercoins_minting_security_desc'] = "In a proof-of-work system, the network is secure as long as no one party controls more than 51% of mining power. To perform an attack, a single attacker must be able to outpace the rest of the network in block generation. This may seem unlikely, but Bitcoin mining pools have approached 51% of the network hashrate in the past. At the time of writing, two mining pools control more than 51% of the Bitcoin network; an attack could be performed by coercing just two people (the pool operators) to collude.</p><p>In Peercoin, an attacker would have to possess 51% of the minting power, which means 51% of all coins if everyone is minting. This makes the attack more difficult as it is unlikely one party would end up owning 51% of the wealth, but also acts as a deterrent to attack because an attack would cause the value of the currency to drop. A party that possesses more than 51% of coins has a vested interest in keeping the value of the coins steady or rising.";
$locale_strings['ru']['get_peercoins_minting_security_desc'] = "In a proof-of-work system, the network is secure as long as no one party controls more than 51% of mining power. To perform an attack, a single attacker must be able to outpace the rest of the network in block generation. This may seem unlikely, but Bitcoin mining pools have approached 51% of the network hashrate in the past. At the time of writing, two mining pools control more than 51% of the Bitcoin network; an attack could be performed by coercing just two people (the pool operators) to collude.</p><p>In Peercoin, an attacker would have to possess 51% of the minting power, which means 51% of all coins if everyone is minting. This makes the attack more difficult as it is unlikely one party would end up owning 51% of the wealth, but also acts as a deterrent to attack because an attack would cause the value of the currency to drop. A party that possesses more than 51% of coins has a vested interest in keeping the value of the coins steady or rising.";
$locale_strings['zh']['get_peercoins_minting_security_desc'] = "In a proof-of-work system, the network is secure as long as no one party controls more than 51% of mining power. To perform an attack, a single attacker must be able to outpace the rest of the network in block generation. This may seem unlikely, but Bitcoin mining pools have approached 51% of the network hashrate in the past. At the time of writing, two mining pools control more than 51% of the Bitcoin network; an attack could be performed by coercing just two people (the pool operators) to collude.</p><p>In Peercoin, an attacker would have to possess 51% of the minting power, which means 51% of all coins if everyone is minting. This makes the attack more difficult as it is unlikely one party would end up owning 51% of the wealth, but also acts as a deterrent to attack because an attack would cause the value of the currency to drop. A party that possesses more than 51% of coins has a vested interest in keeping the value of the coins steady or rising.";

$locale_strings['en']['get_peercoins_minting_what'] = "What is minting, exactly?";
$locale_strings['cat']['get_peercoins_minting_what'] = "What is minting, exactly?";
$locale_strings['es']['get_peercoins_minting_what'] = "What is minting, exactly?";
$locale_strings['fr']['get_peercoins_minting_what'] = "Qu'est-ce que frapper la monnaie, exactement ?";
$locale_strings['gr']['get_peercoins_minting_what'] = "What is minting, exactly?";
$locale_strings['it']['get_peercoins_minting_what'] = "What is minting, exactly?";
$locale_strings['no']['get_peercoins_minting_what'] = "What is minting, exactly?";
$locale_strings['ru']['get_peercoins_minting_what'] = "What is minting, exactly?";
$locale_strings['zh']['get_peercoins_minting_what'] = "What is minting, exactly?";

$locale_strings['en']['get_peercoins_minting_what_desc'] = "All coins in the Peercoin network collect coin age. Your stake is calculated from this coin age, measured by last transaction, and multiplied with the amount of coins (time * coins). Transferred coins lose their age and start a new \"life\" as fresh coins. When you keep coins for 30 days, they are old enough to start the minting process. From that moment on the software tests the \"search space\" given by the coin age, the limited options are tested if they \"solve the puzzle\" like in Bitcoin mining. You can simply think of this by comparing it with a raffle. But it is a raffle that lets you keep the tickets every time you do not win a round. And with it the chance of producing a valid solution of the next puzzle increases. More coins equal more raffle tickets. So 100 coins at an age of 30 days are twice as likely to solve the \"puzzle\" as 50 coins with 30 age days. The maximum age a coin can have is 90 days, after this the coin does not age further. When a puzzle is solved you can mint some percentage of your input, by sending these new coins and the old ones to yourself. With it you \"consume\" your built-up coin age. As you test against a limited number of raffle tickets (the \"limited search space\"), this requires significantly less power. Attacks become more difficult as well, instead of controlling 51% calculating power to take over the block chain, you need 51% of the coins that are put up as stake! When a block is minted, your new coins will be unspendable for a period of 520 blocks (~ 3.6 days with 10 minutes blocks). More information can be found in the Peercoin <a href=\"whitepaper\">whitepaper</a>.";
$locale_strings['cat']['get_peercoins_minting_what_desc'] = "All coins in the Peercoin network collect coin age. Your stake is calculated from this coin age, measured by last transaction, and multiplied with the amount of coins (time * coins). Transferred coins lose their age and start a new \"life\" as fresh coins. When you keep coins for 30 days, they are old enough to start the minting process. From that moment on the software tests the \"search space\" given by the coin age, the limited options are tested if they \"solve the puzzle\" like in Bitcoin mining. You can simply think of this by comparing it with a raffle. But it is a raffle that lets you keep the tickets every time you do not win a round. And with it the chance of producing a valid solution of the next puzzle increases. More coins equal more raffle tickets. So 100 coins at an age of 30 days are twice as likely to solve the \"puzzle\" as 50 coins with 30 age days. The maximum age a coin can have is 90 days, after this the coin does not age further. When a puzzle is solved you can mint some percentage of your input, by sending these new coins and the old ones to yourself. With it you \"consume\" your built-up coin age. As you test against a limited number of raffle tickets (the \"limited search space\"), this requires significantly less power. Attacks become more difficult as well, instead of controlling 51% calculating power to take over the block chain, you need 51% of the coins that are put up as stake! When a block is minted, your new coins will be unspendable for a period of 520 blocks (~ 3.6 days with 10 minutes blocks). More information can be found in the Peercoin <a href=\"whitepaper\">whitepaper</a>.";
$locale_strings['es']['get_peercoins_minting_what_desc'] = "All coins in the Peercoin network collect coin age. Your stake is calculated from this coin age, measured by last transaction, and multiplied with the amount of coins (time * coins). Transferred coins lose their age and start a new \"life\" as fresh coins. When you keep coins for 30 days, they are old enough to start the minting process. From that moment on the software tests the \"search space\" given by the coin age, the limited options are tested if they \"solve the puzzle\" like in Bitcoin mining. You can simply think of this by comparing it with a raffle. But it is a raffle that lets you keep the tickets every time you do not win a round. And with it the chance of producing a valid solution of the next puzzle increases. More coins equal more raffle tickets. So 100 coins at an age of 30 days are twice as likely to solve the \"puzzle\" as 50 coins with 30 age days. The maximum age a coin can have is 90 days, after this the coin does not age further. When a puzzle is solved you can mint some percentage of your input, by sending these new coins and the old ones to yourself. With it you \"consume\" your built-up coin age. As you test against a limited number of raffle tickets (the \"limited search space\"), this requires significantly less power. Attacks become more difficult as well, instead of controlling 51% calculating power to take over the block chain, you need 51% of the coins that are put up as stake! When a block is minted, your new coins will be unspendable for a period of 520 blocks (~ 3.6 days with 10 minutes blocks). More information can be found in the Peercoin <a href=\"whitepaper\">whitepaper</a>.";
$locale_strings['fr']['get_peercoins_minting_what_desc'] = "Dans Peercoin toutes les pièces gagnent en âge. Votre part est calculée à partir de cet âge, mesuré depuis la dernière transaction dans laquelle les pièces apparaissent, et multiplié par le nombre de pièces (temps * pièces). Les pièces transférées perdent leur âge et commencent une nouvelle \"vie\" comme pièces neuves. Quand vous gardez des pièces pendant 30 jours, elle deviennent assez vieilles pour commencer le processus de frappe de monnaie. À partir de ce moment le logiciel teste \"l'espace de recherche\" avec l'âge-pièce, en vérifiant si les options limitées \"résolvent le puzzle\" comme dans l'extraction de bitcoins. Vous pouvez simplement voir cela comme une tombola. Mais une tombola ou vous gardez les tickets chaque fois que vous perdez, et la chance de produire une solution valide au prochain puzzle. Plus de pièces égale plus de tickets de tombola. Donc 100 pièces d'un âge de 30 jours ont deux fois plus de chances de résoudre le \"puzzle\" que 50 pièces d'un âge de 30 jours. L'âge maximum d'une pièce est de 90 jouts, après ça son âge n'augmente plus. Quand un puzzle est résolu vous pouvez frapper un certain pourcentage de votre part, en envoyant ces nouvelles pièces et les anciennes à vous-même. Ainsi vous \"consommez\" l'âge accumulé par vos pièces. Puisque vous testez un nombre limité de tickets de tombola (\"l'espace de recherche\" limité), ceci nécessite moins de puissance. Les attaques deviennent aussi plus difficiles, au lieu du contrôle de 51% de la puissance de calcul pour prendre le pouvoir sur la chaîne de blocs, vous avez besoin de 51% des pièces qui sont utilisées pour frapper la monnaie ! Quand un bloc preuve-de-part est généré, vos nouvelles pièces ne peuvent pas être dépensées pendant une période de 520 blocs (~ 3.6 jours avec un bloc toutes les 10 minutes). Vous pouvez trouver plus d'informations dans le <a href=\"whitepaper\">livre blanc</a> de Peercoin.";
$locale_strings['gr']['get_peercoins_minting_what_desc'] = "All coins in the Peercoin network collect coin age. Your stake is calculated from this coin age, measured by last transaction, and multiplied with the amount of coins (time * coins). Transferred coins lose their age and start a new \"life\" as fresh coins. When you keep coins for 30 days, they are old enough to start the minting process. From that moment on the software tests the \"search space\" given by the coin age, the limited options are tested if they \"solve the puzzle\" like in Bitcoin mining. You can simply think of this by comparing it with a raffle. But it is a raffle that lets you keep the tickets every time you do not win a round. And with it the chance of producing a valid solution of the next puzzle increases. More coins equal more raffle tickets. So 100 coins at an age of 30 days are twice as likely to solve the \"puzzle\" as 50 coins with 30 age days. The maximum age a coin can have is 90 days, after this the coin does not age further. When a puzzle is solved you can mint some percentage of your input, by sending these new coins and the old ones to yourself. With it you \"consume\" your built-up coin age. As you test against a limited number of raffle tickets (the \"limited search space\"), this requires significantly less power. Attacks become more difficult as well, instead of controlling 51% calculating power to take over the block chain, you need 51% of the coins that are put up as stake! When a block is minted, your new coins will be unspendable for a period of 520 blocks (~ 3.6 days with 10 minutes blocks). More information can be found in the Peercoin <a href=\"whitepaper\">whitepaper</a>.";
$locale_strings['it']['get_peercoins_minting_what_desc'] = "All coins in the Peercoin network collect coin age. Your stake is calculated from this coin age, measured by last transaction, and multiplied with the amount of coins (time * coins). Transferred coins lose their age and start a new \"life\" as fresh coins. When you keep coins for 30 days, they are old enough to start the minting process. From that moment on the software tests the \"search space\" given by the coin age, the limited options are tested if they \"solve the puzzle\" like in Bitcoin mining. You can simply think of this by comparing it with a raffle. But it is a raffle that lets you keep the tickets every time you do not win a round. And with it the chance of producing a valid solution of the next puzzle increases. More coins equal more raffle tickets. So 100 coins at an age of 30 days are twice as likely to solve the \"puzzle\" as 50 coins with 30 age days. The maximum age a coin can have is 90 days, after this the coin does not age further. When a puzzle is solved you can mint some percentage of your input, by sending these new coins and the old ones to yourself. With it you \"consume\" your built-up coin age. As you test against a limited number of raffle tickets (the \"limited search space\"), this requires significantly less power. Attacks become more difficult as well, instead of controlling 51% calculating power to take over the block chain, you need 51% of the coins that are put up as stake! When a block is minted, your new coins will be unspendable for a period of 520 blocks (~ 3.6 days with 10 minutes blocks). More information can be found in the Peercoin <a href=\"whitepaper\">whitepaper</a>.";
$locale_strings['no']['get_peercoins_minting_what_desc'] = "All coins in the Peercoin network collect coin age. Your stake is calculated from this coin age, measured by last transaction, and multiplied with the amount of coins (time * coins). Transferred coins lose their age and start a new \"life\" as fresh coins. When you keep coins for 30 days, they are old enough to start the minting process. From that moment on the software tests the \"search space\" given by the coin age, the limited options are tested if they \"solve the puzzle\" like in Bitcoin mining. You can simply think of this by comparing it with a raffle. But it is a raffle that lets you keep the tickets every time you do not win a round. And with it the chance of producing a valid solution of the next puzzle increases. More coins equal more raffle tickets. So 100 coins at an age of 30 days are twice as likely to solve the \"puzzle\" as 50 coins with 30 age days. The maximum age a coin can have is 90 days, after this the coin does not age further. When a puzzle is solved you can mint some percentage of your input, by sending these new coins and the old ones to yourself. With it you \"consume\" your built-up coin age. As you test against a limited number of raffle tickets (the \"limited search space\"), this requires significantly less power. Attacks become more difficult as well, instead of controlling 51% calculating power to take over the block chain, you need 51% of the coins that are put up as stake! When a block is minted, your new coins will be unspendable for a period of 520 blocks (~ 3.6 days with 10 minutes blocks). More information can be found in the Peercoin <a href=\"whitepaper\">whitepaper</a>.";
$locale_strings['ru']['get_peercoins_minting_what_desc'] = "All coins in the Peercoin network collect coin age. Your stake is calculated from this coin age, measured by last transaction, and multiplied with the amount of coins (time * coins). Transferred coins lose their age and start a new \"life\" as fresh coins. When you keep coins for 30 days, they are old enough to start the minting process. From that moment on the software tests the \"search space\" given by the coin age, the limited options are tested if they \"solve the puzzle\" like in Bitcoin mining. You can simply think of this by comparing it with a raffle. But it is a raffle that lets you keep the tickets every time you do not win a round. And with it the chance of producing a valid solution of the next puzzle increases. More coins equal more raffle tickets. So 100 coins at an age of 30 days are twice as likely to solve the \"puzzle\" as 50 coins with 30 age days. The maximum age a coin can have is 90 days, after this the coin does not age further. When a puzzle is solved you can mint some percentage of your input, by sending these new coins and the old ones to yourself. With it you \"consume\" your built-up coin age. As you test against a limited number of raffle tickets (the \"limited search space\"), this requires significantly less power. Attacks become more difficult as well, instead of controlling 51% calculating power to take over the block chain, you need 51% of the coins that are put up as stake! When a block is minted, your new coins will be unspendable for a period of 520 blocks (~ 3.6 days with 10 minutes blocks). More information can be found in the Peercoin <a href=\"whitepaper\">whitepaper</a>.";
$locale_strings['zh']['get_peercoins_minting_what_desc'] = "All coins in the Peercoin network collect coin age. Your stake is calculated from this coin age, measured by last transaction, and multiplied with the amount of coins (time * coins). Transferred coins lose their age and start a new \"life\" as fresh coins. When you keep coins for 30 days, they are old enough to start the minting process. From that moment on the software tests the \"search space\" given by the coin age, the limited options are tested if they \"solve the puzzle\" like in Bitcoin mining. You can simply think of this by comparing it with a raffle. But it is a raffle that lets you keep the tickets every time you do not win a round. And with it the chance of producing a valid solution of the next puzzle increases. More coins equal more raffle tickets. So 100 coins at an age of 30 days are twice as likely to solve the \"puzzle\" as 50 coins with 30 age days. The maximum age a coin can have is 90 days, after this the coin does not age further. When a puzzle is solved you can mint some percentage of your input, by sending these new coins and the old ones to yourself. With it you \"consume\" your built-up coin age. As you test against a limited number of raffle tickets (the \"limited search space\"), this requires significantly less power. Attacks become more difficult as well, instead of controlling 51% calculating power to take over the block chain, you need 51% of the coins that are put up as stake! When a block is minted, your new coins will be unspendable for a period of 520 blocks (~ 3.6 days with 10 minutes blocks). More information can be found in the Peercoin <a href=\"whitepaper\">whitepaper</a>.";

$locale_strings['en']['get_peercoins_minting_return'] = "Minting Return";
$locale_strings['cat']['get_peercoins_minting_return'] = "Minting Return";
$locale_strings['es']['get_peercoins_minting_return'] = "Minting Return";
$locale_strings['fr']['get_peercoins_minting_return'] = "Gains de la frappe de monnaie";
$locale_strings['gr']['get_peercoins_minting_return'] = "Minting Return";
$locale_strings['it']['get_peercoins_minting_return'] = "Minting Return";
$locale_strings['no']['get_peercoins_minting_return'] = "Minting Return";
$locale_strings['ru']['get_peercoins_minting_return'] = "Minting Return";
$locale_strings['zh']['get_peercoins_minting_return'] = "Minting Return";

$locale_strings['en']['get_peercoins_minting_return_desc'] = "Statistically you will get 1% interest on average on your coins per year if you mint. You only mint when your wallet is open, but as the resources use is a lot lower this will not lock up the computer or waste much power. Your wallet is unlocked, but you will still need your passphrase for transactions. An alternative strategy would be to wait until you have a lot of coin age and have a larger chance of minting a block. This would be around 90 days after transaction. However your return will be a little less compared with constant minting. Future wallet version will support in-wallet minting, possibly without decrypting.</p><p>The Peercoin-QT wallet software takes care of this whole process automatically, but it needs some configuration before it can start.";
$locale_strings['cat']['get_peercoins_minting_return_desc'] = "Statistically you will get 1% interest on average on your coins per year if you mint. You only mint when your wallet is open, but as the resources use is a lot lower this will not lock up the computer or waste much power. Your wallet is unlocked, but you will still need your passphrase for transactions. An alternative strategy would be to wait until you have a lot of coin age and have a larger chance of minting a block. This would be around 90 days after transaction. However your return will be a little less compared with constant minting. Future wallet version will support in-wallet minting, possibly without decrypting.</p><p>The Peercoin-QT wallet software takes care of this whole process automatically, but it needs some configuration before it can start.";
$locale_strings['es']['get_peercoins_minting_return_desc'] = "Statistically you will get 1% interest on average on your coins per year if you mint. You only mint when your wallet is open, but as the resources use is a lot lower this will not lock up the computer or waste much power. Your wallet is unlocked, but you will still need your passphrase for transactions. An alternative strategy would be to wait until you have a lot of coin age and have a larger chance of minting a block. This would be around 90 days after transaction. However your return will be a little less compared with constant minting. Future wallet version will support in-wallet minting, possibly without decrypting.</p><p>The Peercoin-QT wallet software takes care of this whole process automatically, but it needs some configuration before it can start.";
$locale_strings['fr']['get_peercoins_minting_return_desc'] = "Statistiquement you gagnerez 1% d'intérêts par an en moyenne si vous frappez la monnaie. Vous frappez la monnaie seulement quand votre portefeuille est ouvert, mais comme les ressources nécessaires sont très faibles cela ne ralentira pas votre ordinateur et ne consommera pas beaucoup d'énergie. Votre portefeuille est dévérouillé, mais vous devrez quand même entrer votre mot de passe pour effectuer des transactions. Une alternative serait d'attendre jusqu'à ce que vous ayez beaucoup d'âge-pièce et une plus grande chance de générer un bloc. Ceci arrivera environ 90 jours après la transaction. Cependant votre gain sera un peu inférieur en comparaison d'une frappe de monnaie continue. Une version future du portefeuille supportera la frappe de monnaie ne nécessitant pas de décrypter le portefeuille.</p><p>Le portefeuille logiciel Peercoin-QT s'occupe de tout ce processus automatiquement, mais il a besoin d'être configuré avant de pouvoir commencer.";
$locale_strings['gr']['get_peercoins_minting_return_desc'] = "Statistically you will get 1% interest on average on your coins per year if you mint. You only mint when your wallet is open, but as the resources use is a lot lower this will not lock up the computer or waste much power. Your wallet is unlocked, but you will still need your passphrase for transactions. An alternative strategy would be to wait until you have a lot of coin age and have a larger chance of minting a block. This would be around 90 days after transaction. However your return will be a little less compared with constant minting. Future wallet version will support in-wallet minting, possibly without decrypting.</p><p>The Peercoin-QT wallet software takes care of this whole process automatically, but it needs some configuration before it can start.";
$locale_strings['it']['get_peercoins_minting_return_desc'] = "Statistically you will get 1% interest on average on your coins per year if you mint. You only mint when your wallet is open, but as the resources use is a lot lower this will not lock up the computer or waste much power. Your wallet is unlocked, but you will still need your passphrase for transactions. An alternative strategy would be to wait until you have a lot of coin age and have a larger chance of minting a block. This would be around 90 days after transaction. However your return will be a little less compared with constant minting. Future wallet version will support in-wallet minting, possibly without decrypting.</p><p>The Peercoin-QT wallet software takes care of this whole process automatically, but it needs some configuration before it can start.";
$locale_strings['no']['get_peercoins_minting_return_desc'] = "Statistically you will get 1% interest on average on your coins per year if you mint. You only mint when your wallet is open, but as the resources use is a lot lower this will not lock up the computer or waste much power. Your wallet is unlocked, but you will still need your passphrase for transactions. An alternative strategy would be to wait until you have a lot of coin age and have a larger chance of minting a block. This would be around 90 days after transaction. However your return will be a little less compared with constant minting. Future wallet version will support in-wallet minting, possibly without decrypting.</p><p>The Peercoin-QT wallet software takes care of this whole process automatically, but it needs some configuration before it can start.";
$locale_strings['ru']['get_peercoins_minting_return_desc'] = "Statistically you will get 1% interest on average on your coins per year if you mint. You only mint when your wallet is open, but as the resources use is a lot lower this will not lock up the computer or waste much power. Your wallet is unlocked, but you will still need your passphrase for transactions. An alternative strategy would be to wait until you have a lot of coin age and have a larger chance of minting a block. This would be around 90 days after transaction. However your return will be a little less compared with constant minting. Future wallet version will support in-wallet minting, possibly without decrypting.</p><p>The Peercoin-QT wallet software takes care of this whole process automatically, but it needs some configuration before it can start.";
$locale_strings['zh']['get_peercoins_minting_return_desc'] = "Statistically you will get 1% interest on average on your coins per year if you mint. You only mint when your wallet is open, but as the resources use is a lot lower this will not lock up the computer or waste much power. Your wallet is unlocked, but you will still need your passphrase for transactions. An alternative strategy would be to wait until you have a lot of coin age and have a larger chance of minting a block. This would be around 90 days after transaction. However your return will be a little less compared with constant minting. Future wallet version will support in-wallet minting, possibly without decrypting.</p><p>The Peercoin-QT wallet software takes care of this whole process automatically, but it needs some configuration before it can start.";

$locale_strings['en']['get_peercoins_minting_howto_start'] = "How to start minting?";
$locale_strings['cat']['get_peercoins_minting_howto_start'] = "How to start minting?";
$locale_strings['es']['get_peercoins_minting_howto_start'] = "How to start minting?";
$locale_strings['fr']['get_peercoins_minting_howto_start'] = "Comment commencer à frapper la monnaie ?";
$locale_strings['gr']['get_peercoins_minting_howto_start'] = "How to start minting?";
$locale_strings['it']['get_peercoins_minting_howto_start'] = "How to start minting?";
$locale_strings['no']['get_peercoins_minting_howto_start'] = "How to start minting?";
$locale_strings['ru']['get_peercoins_minting_howto_start'] = "How to start minting?";
$locale_strings['zh']['get_peercoins_minting_howto_start'] = "How to start minting?";
